Repository seyedali-dev/DevClock-v0.1_TimeEntryService, pull requests merged in 2024-05, with the labels that each got.

#2 Feature/security keycloak ci githubactions Done. Close #1
  .github/workflows/maven-build.yml
  .gitignore
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/TimeEntryServiceApplication.java
  src/main/java/com/seyed/ali/timeentryservice/config/security/SecurityConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/config/security/entrypoints/AuthServiceBearerTokenAccessDeniedHandler.java
  src/main/java/com/seyed/ali/timeentryservice/config/swagger/SwaggerConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TestController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/AuthServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/keycloak/util/KeycloakSecurityUtil.java
  src/main/java/com/seyed/ali/timeentryservice/keycloak/util/converter/KeycloakJwtAuthorityConverter.java
  src/main/java/com/seyed/ali/timeentryservice/response/Result.java
  src/main/resources/.env.properties
  src/main/resources/application-dev.yml
  src/test/java/com/seyed/ali/timeentryservice/TimeEntryServiceApplicationTests.java
  src/test/java/com/seyed/ali/timeentryservice/config/EurekaClientTestConfiguration.java
  src/test/java/com/seyed/ali/timeentryservice/config/TestServiceInstanceListSupplier.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TestControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/keycloak/util/KeycloakSecurityUtilTest.java
  src/test/java/com/seyed/ali/timeentryservice/keycloak/util/converter/KeycloakJwtAuthorityConverterTest.java
  src/test/resources/application-test.yml
Labels: enhancement, new feature

#9 Feature/time entries crud opr done. (Close #3)
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/client/AuthenticationServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/AuthServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/Result.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeEntryDTO.java
  src/main/java/com/seyed/ali/timeentryservice/repository/TimeEntryRepository.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryService.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeParser.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/util/TimeParserTest.java
Labels: enhancement, testing

#15 Implement `getCurrentLoggedInUsersId()` (Close #8)
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/client/AuthenticationServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/config/webclient/WebClientConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/keycloak/util/KeycloakSecurityUtil.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryServiceUtility.java
  src/main/resources/application-dev.yml
  src/test/java/com/seyed/ali/timeentryservice/client/AuthenticationServiceClientTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TestControllerTest.java
  src/test/resources/application-test.yml
Labels: enhancement, testing

#19 Feature/time entries tracker (Close #17 #18)
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/AuthServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeSegment.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeEntryDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeSegmentDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/response/Result.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/response/TimeEntryResponse.java
  src/main/java/com/seyed/ali/timeentryservice/repository/TimeEntryRepository.java
  src/main/java/com/seyed/ali/timeentryservice/repository/TimeSegmentRepository.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryService.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryTrackingService.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryServiceUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeParser.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/util/TimeParserUtilForTests.java
Labels: bug, enhancement, new feature, testing

#21 Hotfix/error handling - Refactored to follow SOLID - Implemented Unit tests (Close #16)
  src/main/java/com/seyed/ali/timeentryservice/exceptions/ResourceNotFoundException.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/repository/TimeEntryRepository.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryService.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryTrackingService.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryUtility.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImplTest.java
Labels: enhancement, testing

#22 hotfix: Refactored to use `ResponseEntity` in controllers (Close #7)
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/AuthServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/TimeEntryServiceHandlerAdvice.java
Labels: enhancement, testing

#23 hotfix: Implement Error Handling for Tracking Time (Close #11)
  src/main/java/com/seyed/ali/timeentryservice/exceptions/OperationNotSupportedException.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/handler/TimeEntryServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
Labels: enhancement

#24 Feature/input validation - Close #6
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/annotation/OptionalField.java
  src/main/java/com/seyed/ali/timeentryservice/annotation/OptionalFieldValidator.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/handler/TimeEntryServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeBillingDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeEntryDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/dto/TimeSegmentDTO.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryServiceUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeParser.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingControllerTest.java
Labels: enhancement

#27 Feature/redis state management - Close #13
  .gitignore
  pom.xml
  src/main/java/com/seyed/ali/timeentryservice/config/cache/RedisConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingController.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeSegment.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/cache/TimeEntryCacheManager.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryService.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryTrackingService.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/converter/TimeEntryConverter.java
  src/main/resources/application-dev.yml
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImplTest.java
Labels: bug, enhancement, new feature

#30 Hotfix/clientservice solid completed - (Close #29)
  src/main/java/com/seyed/ali/timeentryservice/client/AuthenticationServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/client/ProjectServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/client/ServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/client/TaskServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/config/swagger/SwaggerConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/config/webclient/WebClientConfiguration.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TestController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryAssignmentController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryController.java
  src/main/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingController.java
  src/main/java/com/seyed/ali/timeentryservice/exceptions/handler/TimeEntryServiceHandlerAdvice.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/enums/TaskStatus.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TaskDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TimeBillingDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TimeEntryDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TimeSegmentDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/response/Result.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/response/TimeEntryResponse.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryAssignmentServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryAssignmentService.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryService.java
  src/main/java/com/seyed/ali/timeentryservice/service/interfaces/TimeEntryTrackingService.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/converter/TimeEntryConverter.java
  src/test/java/com/seyed/ali/timeentryservice/client/AuthenticationServiceClientTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImplTest.java
Labels: bug, enhancement

#31 feat: project association while creating time entry. (Close #28)
  src/main/java/com/seyed/ali/timeentryservice/client/TaskServiceClient.java
  src/main/java/com/seyed/ali/timeentryservice/model/domain/TimeEntry.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TimeBillingDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/TimeEntryDTO.java
  src/main/java/com/seyed/ali/timeentryservice/model/payload/response/TimeEntryResponse.java
  src/main/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImpl.java
  src/main/java/com/seyed/ali/timeentryservice/util/TimeEntryUtility.java
  src/main/java/com/seyed/ali/timeentryservice/util/converter/TimeEntryConverter.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/controller/TimeEntryTrackingControllerTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryServiceImplTest.java
  src/test/java/com/seyed/ali/timeentryservice/service/TimeEntryTrackingServiceImplTest.java
Labels: enhancement, new feature
